routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Livewire\User\Create;
use App\Http\Livewire\User\Register;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::post('/user/create',[UserController::class, 'store']);
Route::resource('user', UserController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Category extends Model
{
    use HasFactory;
    use softDeletes;

    protected $fillable = [
        'id',
        'name',
        'description'
    ];


}

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, softDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'mail_address',
        'password',
        'address',
        'phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        // 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Barryvdh\Debugbar\Facade as Debugbar;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(20);
        return view('user.list',[
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $validated = $request->validated();
        $validated['password'] = Hash::make($validated['password']);
        User::create($validated);
        return redirect('/user')->with('success','Thêm mới người dùng thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user = User::find($id);
        return view('user.detail',['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);
        return view('user.edit',['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        //
        $user = User::find($id);
        $user->name = $request->name;
        $user->phone = $request->phone;
        $user->address = $request->address;
        $user->save();
        
        return view('user.detail',['user' => $user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // 
        $user = User::find($id);
        $user->delete();

        return redirect()->route('user.index')
            ->with('success', 'Xoá thành công tài khoản');
    }
}

resources/views/user/detail.blade.php
<x-home>
    <h3 style="text-align: center;">Danh sách tài khoản</h3>
    <div>
        <table style="width:100%;border: 1px solid black;
            border-collapse: collapse;">
            <tr>
                <th>STT</th>
                <th>Email</th>
                <th>Tên</th>
                <th>Địa chỉ</th>
                <th>Số điện thoại</th>
            </tr>
            <tr>
                <th>1</th>
                <th>{{ $user['mail_address'] }}</th>
                <th>{{ $user['name'] }}</th>
                <th>{{ $user['address']}}</th>
                <th>{{ $user['phone']}}</th>
            </tr>
        </table>
    </div>
    
</x-home>

resources/views/user/edit.blade.php
<x-home>
    <div> 
        <h3>Thông tin</h3>
        <form action="{{ route('user.update',$user['id']) }}" method="post">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label class="{{ $errors->has('name') ? 'text-danger' : '' }}" for="name" > Tên </label>
                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" placeholder="Tên" value="{{ $user['name'] }}">
            @if ($errors->has('name'))
                <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('phone') ? 'text-danger' : '' }}" > Số điện thoại </label>
                <input type="text" class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" name="phone" placeholder="Số điện thoại" value="{{ $user['phone'] }}" for="phone">
            @if ($errors->has('phone'))
                <span class="text-danger">{{ $errors->first('phone') }}</span>
            @endif 
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('address') ? 'text-danger' : '' }}"  for="address"> Địa chỉ </label>
                <input type="text" class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" name="address" placeholder="Địa chỉ" value="{{ $user['address'] }}">
            @if ($errors->has('address'))
                <span class="text-danger">{{ $errors->first('address') }}</span>
            @endif
            </div>
            @if (count($errors->all()) > 0)
                <h5 style="text-align:center; margin-top: 20px;">Sửa thông tin tài khoản thất bại</h5>
            @endif
            <div>
                <button class="btn btn-primary" type="submit">Sửa</button>
            </div>  
        </form>
    </div>
</x-home>

resources/views/user/list.blade.php
<x-home>
    <h3 style="text-align: center;">Danh sách tài khoản</h3>
    <div>
        @if (session('success'))
            <div class="alert alert-success" style="text-align: center;">
                {{ session('success') }}
            </div>
        @endif
        @php
            $page = Request::get('page') ? Request::get('page') : 1;
        @endphp
        <table style="width:100%;border: 1px solid black;
    border-collapse: collapse;">
            <tr>
                <th>STT</th>
                <th>Email</th>
                <th>Tên</th>
                <th>Địa chỉ</th>
                <th>Số điện thoại</th>
            </tr>
            @foreach ($users as $user)
            <tr>
                <th>{{ $loop->index + ($page-1) * 20 + 1 }}</th>
                <th>{{ $user['mail_address'] }}</th>
                <th><a href="{{ route('user.show',['user' => $user['id']] ) }}"> {{ $user['name'] }} </a></th>
                <th>{{ $user['address']}}</th>
                <th>{{ $user['phone']}}</th>
                <th>
                    <form action="{{ route('user.destroy',['user' => $user->id])}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" >Xoá</button>
                        <a href="{{ route('user.edit',['user' => $user->id])}}">Edit</a>
                    </form>
                </th>
            </tr>
            
            @endforeach
        </table>
    </div>
    <div style="width:100% ; margin-top: 20px;">
        <span> {{ $users->links('pagination::bootstrap-4') }} </span>
    </div>
   
    
</x-home>

resources/views/user/register.blade.php
<x-home>
    <div> 
        <h3>Đăng Kí</h3>
        <form action="{{ route('user.store') }}" method="post">
            {{ csrf_field() }}
            <div class="form-group">
                <label class="{{ $errors->has('name') ? 'text-danger' : '' }}" for="name"> Tên </label>
                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" placeholder="Tên">
            @if ($errors->has('name'))
                <span class="text-danger">{{ $errors->first('name') }}</span>
            @endif
            </div>
            <div  class="form-group">
                <label class="{{ $errors->has('mail_address') ? 'text-danger' : '' }}" for="mail_address"> Email </label>
                <input type="text" class="form-control {{ $errors->has('mail_address') ? 'is-invalid' : '' }}" name="mail_address" placeholder="Email">
            @if ($errors->has('mail_address'))
                <span class="text-danger">{{ $errors->first('mail_address') }}</span>
            @endif
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('password') ? 'text-danger' : '' }}" for="password"> Mật khẩu </label>
                <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }} " name="password" placeholder="Mật khẩu">
            @if ($errors->has('password'))
                <span class="text-danger">{{ $errors->first('password') }}</span>
            @endif  
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('password_confirmation') ? 'text-danger' : '' }}"  for="password_confirmation"> Xác nhận mật khẩu </label>
                <input type="password" class="form-control {{ $errors->has('password_confirmation') ? 'is-invalid' : '' }}" name="password_confirmation" placeholder="Xác nhận mật khẩu" >
            @if ($errors->has('password_confirmation'))
                <span class="text-danger">{{ $errors->first('password_confirmation') }}</span>
            @endif
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('phone') ? 'text-danger' : '' }}" for="phone"> Số điện thoại </label>
                <input type="text" class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" name="phone" placeholder="Số điện thoại">
            @if ($errors->has('phone'))
                <span class="text-danger">{{ $errors->first('phone') }}</span>
            @endif 
            </div>
            <div class="form-group">
                <label class="{{ $errors->has('address') ? 'text-danger' : '' }}" for="address"> Địa chỉ </label>
                <input type="text" class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" name="address" placeholder="Địa chỉ">
            @if ($errors->has('address'))
                <span class="text-danger">{{ $errors->first('address') }}</span>
            @endif
            </div>
            @if (count($errors->all()) > 0)
                <h5 style="text-align:center; margin-top: 20px;">Tạo tài khoản thất bại</h5>
            @endif
            <div>
                <button class="btn btn-primary" type="submit">Đăng kí</button>
            </div>  
        </form>
    </div>
</x-home>